package com.zuihuibao.web.model;

import java.util.Date;

public class UserInfo {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.user_id
   *
   * @mbggenerated
   */
  private Long userId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.wechat_no
   *
   * @mbggenerated
   */
  private String wechatNo;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.mobile
   *
   * @mbggenerated
   */
  private String mobile;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.coupon_balance
   *
   * @mbggenerated
   */
  private Double couponBalance;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.create_time
   *
   * @mbggenerated
   */
  private Date createTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.update_time
   *
   * @mbggenerated
   */
  private Date updateTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.nickname
   *
   * @mbggenerated
   */
  private String nickname;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.sex
   *
   * @mbggenerated
   */
  private Integer sex;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.city
   *
   * @mbggenerated
   */
  private String city;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.province
   *
   * @mbggenerated
   */
  private String province;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.unionid
   *
   * @mbggenerated
   */
  private String unionid;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.integral
   *
   * @mbggenerated
   */
  private Integer integral;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.channel_id
   *
   * @mbggenerated
   */
  private String channelId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.recommender_id
   *
   * @mbggenerated
   */
  private Long recommenderId;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.recommend_time
   *
   * @mbggenerated
   */
  private Date recommendTime;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.recommend_mobile
   *
   * @mbggenerated
   */
  private String recommendMobile;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.realname
   *
   * @mbggenerated
   */
  private String realname;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.isagent
   *
   * @mbggenerated
   */
  private Integer isagent;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.bank_card
   *
   * @mbggenerated
   */
  private String bankCard;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.subscribe
   *
   * @mbggenerated
   */
  private Integer subscribe;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.thirdparty_account
   *
   * @mbggenerated
   */
  private String thirdpartyAccount;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.rongyun_token
   *
   * @mbggenerated
   */
  private String rongyunToken;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.device_token
   *
   * @mbggenerated
   */
  private String deviceToken;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.city_area
   *
   * @mbggenerated
   */
  private String cityArea;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column user_info.auth_realname
   *
   * @mbggenerated
   */
  private String authRealname;

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user_info
   *
   * @mbggenerated
   */
  public UserInfo(Long userId, String wechatNo, String mobile, Double couponBalance,
      Date createTime, Date updateTime, String nickname, Integer sex, String city, String province,
      String unionid, Integer integral, String channelId, Long recommenderId, Date recommendTime,
      String recommendMobile, String realname, Integer isagent, String bankCard, Integer subscribe,
      String thirdpartyAccount, String rongyunToken, String deviceToken, String cityArea,
      String authRealname) {
    this.userId = userId;
    this.wechatNo = wechatNo;
    this.mobile = mobile;
    this.couponBalance = couponBalance;
    this.createTime = createTime;
    this.updateTime = updateTime;
    this.nickname = nickname;
    this.sex = sex;
    this.city = city;
    this.province = province;
    this.unionid = unionid;
    this.integral = integral;
    this.channelId = channelId;
    this.recommenderId = recommenderId;
    this.recommendTime = recommendTime;
    this.recommendMobile = recommendMobile;
    this.realname = realname;
    this.isagent = isagent;
    this.bankCard = bankCard;
    this.subscribe = subscribe;
    this.thirdpartyAccount = thirdpartyAccount;
    this.rongyunToken = rongyunToken;
    this.deviceToken = deviceToken;
    this.cityArea = cityArea;
    this.authRealname = authRealname;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.user_id
   *
   * @return the value of user_info.user_id
   * @mbggenerated
   */
  public Long getUserId() {
    return userId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.wechat_no
   *
   * @return the value of user_info.wechat_no
   * @mbggenerated
   */
  public String getWechatNo() {
    return wechatNo;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.mobile
   *
   * @return the value of user_info.mobile
   * @mbggenerated
   */
  public String getMobile() {
    return mobile;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.coupon_balance
   *
   * @return the value of user_info.coupon_balance
   * @mbggenerated
   */
  public Double getCouponBalance() {
    return couponBalance;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.create_time
   *
   * @return the value of user_info.create_time
   * @mbggenerated
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.update_time
   *
   * @return the value of user_info.update_time
   * @mbggenerated
   */
  public Date getUpdateTime() {
    return updateTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.nickname
   *
   * @return the value of user_info.nickname
   * @mbggenerated
   */
  public String getNickname() {
    return nickname;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.sex
   *
   * @return the value of user_info.sex
   * @mbggenerated
   */
  public Integer getSex() {
    return sex;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.city
   *
   * @return the value of user_info.city
   * @mbggenerated
   */
  public String getCity() {
    return city;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.province
   *
   * @return the value of user_info.province
   * @mbggenerated
   */
  public String getProvince() {
    return province;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.unionid
   *
   * @return the value of user_info.unionid
   * @mbggenerated
   */
  public String getUnionid() {
    return unionid;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.integral
   *
   * @return the value of user_info.integral
   * @mbggenerated
   */
  public Integer getIntegral() {
    return integral;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.channel_id
   *
   * @return the value of user_info.channel_id
   * @mbggenerated
   */
  public String getChannelId() {
    return channelId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.recommender_id
   *
   * @return the value of user_info.recommender_id
   * @mbggenerated
   */
  public Long getRecommenderId() {
    return recommenderId;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.recommend_time
   *
   * @return the value of user_info.recommend_time
   * @mbggenerated
   */
  public Date getRecommendTime() {
    return recommendTime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.recommend_mobile
   *
   * @return the value of user_info.recommend_mobile
   * @mbggenerated
   */
  public String getRecommendMobile() {
    return recommendMobile;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.realname
   *
   * @return the value of user_info.realname
   * @mbggenerated
   */
  public String getRealname() {
    return realname;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.isagent
   *
   * @return the value of user_info.isagent
   * @mbggenerated
   */
  public Integer getIsagent() {
    return isagent;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.bank_card
   *
   * @return the value of user_info.bank_card
   * @mbggenerated
   */
  public String getBankCard() {
    return bankCard;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.subscribe
   *
   * @return the value of user_info.subscribe
   * @mbggenerated
   */
  public Integer getSubscribe() {
    return subscribe;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.thirdparty_account
   *
   * @return the value of user_info.thirdparty_account
   * @mbggenerated
   */
  public String getThirdpartyAccount() {
    return thirdpartyAccount;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.rongyun_token
   *
   * @return the value of user_info.rongyun_token
   * @mbggenerated
   */
  public String getRongyunToken() {
    return rongyunToken;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.device_token
   *
   * @return the value of user_info.device_token
   * @mbggenerated
   */
  public String getDeviceToken() {
    return deviceToken;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.city_area
   *
   * @return the value of user_info.city_area
   * @mbggenerated
   */
  public String getCityArea() {
    return cityArea;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column user_info.auth_realname
   *
   * @return the value of user_info.auth_realname
   * @mbggenerated
   */
  public String getAuthRealname() {
    return authRealname;
  }
}