package com.zuihuibao.web.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserInfoExample {
  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table user_info
   *
   * @mbggenerated
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table user_info
   *
   * @mbggenerated
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table user_info
   *
   * @mbggenerated
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user_info
   *
   * @mbggenerated
   */
  public UserInfoExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user_info
   *
   * @mbggenerated
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user_info
   *
   * @mbggenerated
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user_info
   *
   * @mbggenerated
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user_info
   *
   * @mbggenerated
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user_info
   *
   * @mbggenerated
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user_info
   *
   * @mbggenerated
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user_info
   *
   * @mbggenerated
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user_info
   *
   * @mbggenerated
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user_info
   *
   * @mbggenerated
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table user_info
   *
   * @mbggenerated
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table user_info
   *
   * @mbggenerated
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andUserIdIsNull() {
      addCriterion("user_id is null");
      return (Criteria) this;
    }

    public Criteria andUserIdIsNotNull() {
      addCriterion("user_id is not null");
      return (Criteria) this;
    }

    public Criteria andUserIdEqualTo(Long value) {
      addCriterion("user_id =", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotEqualTo(Long value) {
      addCriterion("user_id <>", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdGreaterThan(Long value) {
      addCriterion("user_id >", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
      addCriterion("user_id >=", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdLessThan(Long value) {
      addCriterion("user_id <", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdLessThanOrEqualTo(Long value) {
      addCriterion("user_id <=", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdIn(List<Long> values) {
      addCriterion("user_id in", values, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotIn(List<Long> values) {
      addCriterion("user_id not in", values, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdBetween(Long value1, Long value2) {
      addCriterion("user_id between", value1, value2, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotBetween(Long value1, Long value2) {
      addCriterion("user_id not between", value1, value2, "userId");
      return (Criteria) this;
    }

    public Criteria andWechatNoIsNull() {
      addCriterion("wechat_no is null");
      return (Criteria) this;
    }

    public Criteria andWechatNoIsNotNull() {
      addCriterion("wechat_no is not null");
      return (Criteria) this;
    }

    public Criteria andWechatNoEqualTo(String value) {
      addCriterion("wechat_no =", value, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoNotEqualTo(String value) {
      addCriterion("wechat_no <>", value, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoGreaterThan(String value) {
      addCriterion("wechat_no >", value, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoGreaterThanOrEqualTo(String value) {
      addCriterion("wechat_no >=", value, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoLessThan(String value) {
      addCriterion("wechat_no <", value, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoLessThanOrEqualTo(String value) {
      addCriterion("wechat_no <=", value, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoLike(String value) {
      addCriterion("wechat_no like", value, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoNotLike(String value) {
      addCriterion("wechat_no not like", value, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoIn(List<String> values) {
      addCriterion("wechat_no in", values, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoNotIn(List<String> values) {
      addCriterion("wechat_no not in", values, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoBetween(String value1, String value2) {
      addCriterion("wechat_no between", value1, value2, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andWechatNoNotBetween(String value1, String value2) {
      addCriterion("wechat_no not between", value1, value2, "wechatNo");
      return (Criteria) this;
    }

    public Criteria andMobileIsNull() {
      addCriterion("mobile is null");
      return (Criteria) this;
    }

    public Criteria andMobileIsNotNull() {
      addCriterion("mobile is not null");
      return (Criteria) this;
    }

    public Criteria andMobileEqualTo(String value) {
      addCriterion("mobile =", value, "mobile");
      return (Criteria) this;
    }

    public Criteria andMobileNotEqualTo(String value) {
      addCriterion("mobile <>", value, "mobile");
      return (Criteria) this;
    }

    public Criteria andMobileGreaterThan(String value) {
      addCriterion("mobile >", value, "mobile");
      return (Criteria) this;
    }

    public Criteria andMobileGreaterThanOrEqualTo(String value) {
      addCriterion("mobile >=", value, "mobile");
      return (Criteria) this;
    }

    public Criteria andMobileLessThan(String value) {
      addCriterion("mobile <", value, "mobile");
      return (Criteria) this;
    }

    public Criteria andMobileLessThanOrEqualTo(String value) {
      addCriterion("mobile <=", value, "mobile");
      return (Criteria) this;
    }

    public Criteria andMobileLike(String value) {
      addCriterion("mobile like", value, "mobile");
      return (Criteria) this;
    }

    public Criteria andMobileNotLike(String value) {
      addCriterion("mobile not like", value, "mobile");
      return (Criteria) this;
    }

    public Criteria andMobileIn(List<String> values) {
      addCriterion("mobile in", values, "mobile");
      return (Criteria) this;
    }

    public Criteria andMobileNotIn(List<String> values) {
      addCriterion("mobile not in", values, "mobile");
      return (Criteria) this;
    }

    public Criteria andMobileBetween(String value1, String value2) {
      addCriterion("mobile between", value1, value2, "mobile");
      return (Criteria) this;
    }

    public Criteria andMobileNotBetween(String value1, String value2) {
      addCriterion("mobile not between", value1, value2, "mobile");
      return (Criteria) this;
    }

    public Criteria andCouponBalanceIsNull() {
      addCriterion("coupon_balance is null");
      return (Criteria) this;
    }

    public Criteria andCouponBalanceIsNotNull() {
      addCriterion("coupon_balance is not null");
      return (Criteria) this;
    }

    public Criteria andCouponBalanceEqualTo(Double value) {
      addCriterion("coupon_balance =", value, "couponBalance");
      return (Criteria) this;
    }

    public Criteria andCouponBalanceNotEqualTo(Double value) {
      addCriterion("coupon_balance <>", value, "couponBalance");
      return (Criteria) this;
    }

    public Criteria andCouponBalanceGreaterThan(Double value) {
      addCriterion("coupon_balance >", value, "couponBalance");
      return (Criteria) this;
    }

    public Criteria andCouponBalanceGreaterThanOrEqualTo(Double value) {
      addCriterion("coupon_balance >=", value, "couponBalance");
      return (Criteria) this;
    }

    public Criteria andCouponBalanceLessThan(Double value) {
      addCriterion("coupon_balance <", value, "couponBalance");
      return (Criteria) this;
    }

    public Criteria andCouponBalanceLessThanOrEqualTo(Double value) {
      addCriterion("coupon_balance <=", value, "couponBalance");
      return (Criteria) this;
    }

    public Criteria andCouponBalanceIn(List<Double> values) {
      addCriterion("coupon_balance in", values, "couponBalance");
      return (Criteria) this;
    }

    public Criteria andCouponBalanceNotIn(List<Double> values) {
      addCriterion("coupon_balance not in", values, "couponBalance");
      return (Criteria) this;
    }

    public Criteria andCouponBalanceBetween(Double value1, Double value2) {
      addCriterion("coupon_balance between", value1, value2, "couponBalance");
      return (Criteria) this;
    }

    public Criteria andCouponBalanceNotBetween(Double value1, Double value2) {
      addCriterion("coupon_balance not between", value1, value2, "couponBalance");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIsNull() {
      addCriterion("create_time is null");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIsNotNull() {
      addCriterion("create_time is not null");
      return (Criteria) this;
    }

    public Criteria andCreateTimeEqualTo(Date value) {
      addCriterion("create_time =", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotEqualTo(Date value) {
      addCriterion("create_time <>", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeGreaterThan(Date value) {
      addCriterion("create_time >", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("create_time >=", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeLessThan(Date value) {
      addCriterion("create_time <", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
      addCriterion("create_time <=", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIn(List<Date> values) {
      addCriterion("create_time in", values, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotIn(List<Date> values) {
      addCriterion("create_time not in", values, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeBetween(Date value1, Date value2) {
      addCriterion("create_time between", value1, value2, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
      addCriterion("create_time not between", value1, value2, "createTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIsNull() {
      addCriterion("update_time is null");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIsNotNull() {
      addCriterion("update_time is not null");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeEqualTo(Date value) {
      addCriterion("update_time =", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotEqualTo(Date value) {
      addCriterion("update_time <>", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeGreaterThan(Date value) {
      addCriterion("update_time >", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("update_time >=", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeLessThan(Date value) {
      addCriterion("update_time <", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
      addCriterion("update_time <=", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIn(List<Date> values) {
      addCriterion("update_time in", values, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotIn(List<Date> values) {
      addCriterion("update_time not in", values, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeBetween(Date value1, Date value2) {
      addCriterion("update_time between", value1, value2, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
      addCriterion("update_time not between", value1, value2, "updateTime");
      return (Criteria) this;
    }

    public Criteria andNicknameIsNull() {
      addCriterion("nickname is null");
      return (Criteria) this;
    }

    public Criteria andNicknameIsNotNull() {
      addCriterion("nickname is not null");
      return (Criteria) this;
    }

    public Criteria andNicknameEqualTo(String value) {
      addCriterion("nickname =", value, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameNotEqualTo(String value) {
      addCriterion("nickname <>", value, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameGreaterThan(String value) {
      addCriterion("nickname >", value, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameGreaterThanOrEqualTo(String value) {
      addCriterion("nickname >=", value, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameLessThan(String value) {
      addCriterion("nickname <", value, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameLessThanOrEqualTo(String value) {
      addCriterion("nickname <=", value, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameLike(String value) {
      addCriterion("nickname like", value, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameNotLike(String value) {
      addCriterion("nickname not like", value, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameIn(List<String> values) {
      addCriterion("nickname in", values, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameNotIn(List<String> values) {
      addCriterion("nickname not in", values, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameBetween(String value1, String value2) {
      addCriterion("nickname between", value1, value2, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameNotBetween(String value1, String value2) {
      addCriterion("nickname not between", value1, value2, "nickname");
      return (Criteria) this;
    }

    public Criteria andSexIsNull() {
      addCriterion("sex is null");
      return (Criteria) this;
    }

    public Criteria andSexIsNotNull() {
      addCriterion("sex is not null");
      return (Criteria) this;
    }

    public Criteria andSexEqualTo(Integer value) {
      addCriterion("sex =", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexNotEqualTo(Integer value) {
      addCriterion("sex <>", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexGreaterThan(Integer value) {
      addCriterion("sex >", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexGreaterThanOrEqualTo(Integer value) {
      addCriterion("sex >=", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexLessThan(Integer value) {
      addCriterion("sex <", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexLessThanOrEqualTo(Integer value) {
      addCriterion("sex <=", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexIn(List<Integer> values) {
      addCriterion("sex in", values, "sex");
      return (Criteria) this;
    }

    public Criteria andSexNotIn(List<Integer> values) {
      addCriterion("sex not in", values, "sex");
      return (Criteria) this;
    }

    public Criteria andSexBetween(Integer value1, Integer value2) {
      addCriterion("sex between", value1, value2, "sex");
      return (Criteria) this;
    }

    public Criteria andSexNotBetween(Integer value1, Integer value2) {
      addCriterion("sex not between", value1, value2, "sex");
      return (Criteria) this;
    }

    public Criteria andCityIsNull() {
      addCriterion("city is null");
      return (Criteria) this;
    }

    public Criteria andCityIsNotNull() {
      addCriterion("city is not null");
      return (Criteria) this;
    }

    public Criteria andCityEqualTo(String value) {
      addCriterion("city =", value, "city");
      return (Criteria) this;
    }

    public Criteria andCityNotEqualTo(String value) {
      addCriterion("city <>", value, "city");
      return (Criteria) this;
    }

    public Criteria andCityGreaterThan(String value) {
      addCriterion("city >", value, "city");
      return (Criteria) this;
    }

    public Criteria andCityGreaterThanOrEqualTo(String value) {
      addCriterion("city >=", value, "city");
      return (Criteria) this;
    }

    public Criteria andCityLessThan(String value) {
      addCriterion("city <", value, "city");
      return (Criteria) this;
    }

    public Criteria andCityLessThanOrEqualTo(String value) {
      addCriterion("city <=", value, "city");
      return (Criteria) this;
    }

    public Criteria andCityLike(String value) {
      addCriterion("city like", value, "city");
      return (Criteria) this;
    }

    public Criteria andCityNotLike(String value) {
      addCriterion("city not like", value, "city");
      return (Criteria) this;
    }

    public Criteria andCityIn(List<String> values) {
      addCriterion("city in", values, "city");
      return (Criteria) this;
    }

    public Criteria andCityNotIn(List<String> values) {
      addCriterion("city not in", values, "city");
      return (Criteria) this;
    }

    public Criteria andCityBetween(String value1, String value2) {
      addCriterion("city between", value1, value2, "city");
      return (Criteria) this;
    }

    public Criteria andCityNotBetween(String value1, String value2) {
      addCriterion("city not between", value1, value2, "city");
      return (Criteria) this;
    }

    public Criteria andProvinceIsNull() {
      addCriterion("province is null");
      return (Criteria) this;
    }

    public Criteria andProvinceIsNotNull() {
      addCriterion("province is not null");
      return (Criteria) this;
    }

    public Criteria andProvinceEqualTo(String value) {
      addCriterion("province =", value, "province");
      return (Criteria) this;
    }

    public Criteria andProvinceNotEqualTo(String value) {
      addCriterion("province <>", value, "province");
      return (Criteria) this;
    }

    public Criteria andProvinceGreaterThan(String value) {
      addCriterion("province >", value, "province");
      return (Criteria) this;
    }

    public Criteria andProvinceGreaterThanOrEqualTo(String value) {
      addCriterion("province >=", value, "province");
      return (Criteria) this;
    }

    public Criteria andProvinceLessThan(String value) {
      addCriterion("province <", value, "province");
      return (Criteria) this;
    }

    public Criteria andProvinceLessThanOrEqualTo(String value) {
      addCriterion("province <=", value, "province");
      return (Criteria) this;
    }

    public Criteria andProvinceLike(String value) {
      addCriterion("province like", value, "province");
      return (Criteria) this;
    }

    public Criteria andProvinceNotLike(String value) {
      addCriterion("province not like", value, "province");
      return (Criteria) this;
    }

    public Criteria andProvinceIn(List<String> values) {
      addCriterion("province in", values, "province");
      return (Criteria) this;
    }

    public Criteria andProvinceNotIn(List<String> values) {
      addCriterion("province not in", values, "province");
      return (Criteria) this;
    }

    public Criteria andProvinceBetween(String value1, String value2) {
      addCriterion("province between", value1, value2, "province");
      return (Criteria) this;
    }

    public Criteria andProvinceNotBetween(String value1, String value2) {
      addCriterion("province not between", value1, value2, "province");
      return (Criteria) this;
    }

    public Criteria andUnionidIsNull() {
      addCriterion("unionid is null");
      return (Criteria) this;
    }

    public Criteria andUnionidIsNotNull() {
      addCriterion("unionid is not null");
      return (Criteria) this;
    }

    public Criteria andUnionidEqualTo(String value) {
      addCriterion("unionid =", value, "unionid");
      return (Criteria) this;
    }

    public Criteria andUnionidNotEqualTo(String value) {
      addCriterion("unionid <>", value, "unionid");
      return (Criteria) this;
    }

    public Criteria andUnionidGreaterThan(String value) {
      addCriterion("unionid >", value, "unionid");
      return (Criteria) this;
    }

    public Criteria andUnionidGreaterThanOrEqualTo(String value) {
      addCriterion("unionid >=", value, "unionid");
      return (Criteria) this;
    }

    public Criteria andUnionidLessThan(String value) {
      addCriterion("unionid <", value, "unionid");
      return (Criteria) this;
    }

    public Criteria andUnionidLessThanOrEqualTo(String value) {
      addCriterion("unionid <=", value, "unionid");
      return (Criteria) this;
    }

    public Criteria andUnionidLike(String value) {
      addCriterion("unionid like", value, "unionid");
      return (Criteria) this;
    }

    public Criteria andUnionidNotLike(String value) {
      addCriterion("unionid not like", value, "unionid");
      return (Criteria) this;
    }

    public Criteria andUnionidIn(List<String> values) {
      addCriterion("unionid in", values, "unionid");
      return (Criteria) this;
    }

    public Criteria andUnionidNotIn(List<String> values) {
      addCriterion("unionid not in", values, "unionid");
      return (Criteria) this;
    }

    public Criteria andUnionidBetween(String value1, String value2) {
      addCriterion("unionid between", value1, value2, "unionid");
      return (Criteria) this;
    }

    public Criteria andUnionidNotBetween(String value1, String value2) {
      addCriterion("unionid not between", value1, value2, "unionid");
      return (Criteria) this;
    }

    public Criteria andIntegralIsNull() {
      addCriterion("integral is null");
      return (Criteria) this;
    }

    public Criteria andIntegralIsNotNull() {
      addCriterion("integral is not null");
      return (Criteria) this;
    }

    public Criteria andIntegralEqualTo(Integer value) {
      addCriterion("integral =", value, "integral");
      return (Criteria) this;
    }

    public Criteria andIntegralNotEqualTo(Integer value) {
      addCriterion("integral <>", value, "integral");
      return (Criteria) this;
    }

    public Criteria andIntegralGreaterThan(Integer value) {
      addCriterion("integral >", value, "integral");
      return (Criteria) this;
    }

    public Criteria andIntegralGreaterThanOrEqualTo(Integer value) {
      addCriterion("integral >=", value, "integral");
      return (Criteria) this;
    }

    public Criteria andIntegralLessThan(Integer value) {
      addCriterion("integral <", value, "integral");
      return (Criteria) this;
    }

    public Criteria andIntegralLessThanOrEqualTo(Integer value) {
      addCriterion("integral <=", value, "integral");
      return (Criteria) this;
    }

    public Criteria andIntegralIn(List<Integer> values) {
      addCriterion("integral in", values, "integral");
      return (Criteria) this;
    }

    public Criteria andIntegralNotIn(List<Integer> values) {
      addCriterion("integral not in", values, "integral");
      return (Criteria) this;
    }

    public Criteria andIntegralBetween(Integer value1, Integer value2) {
      addCriterion("integral between", value1, value2, "integral");
      return (Criteria) this;
    }

    public Criteria andIntegralNotBetween(Integer value1, Integer value2) {
      addCriterion("integral not between", value1, value2, "integral");
      return (Criteria) this;
    }

    public Criteria andChannelIdIsNull() {
      addCriterion("channel_id is null");
      return (Criteria) this;
    }

    public Criteria andChannelIdIsNotNull() {
      addCriterion("channel_id is not null");
      return (Criteria) this;
    }

    public Criteria andChannelIdEqualTo(String value) {
      addCriterion("channel_id =", value, "channelId");
      return (Criteria) this;
    }

    public Criteria andChannelIdNotEqualTo(String value) {
      addCriterion("channel_id <>", value, "channelId");
      return (Criteria) this;
    }

    public Criteria andChannelIdGreaterThan(String value) {
      addCriterion("channel_id >", value, "channelId");
      return (Criteria) this;
    }

    public Criteria andChannelIdGreaterThanOrEqualTo(String value) {
      addCriterion("channel_id >=", value, "channelId");
      return (Criteria) this;
    }

    public Criteria andChannelIdLessThan(String value) {
      addCriterion("channel_id <", value, "channelId");
      return (Criteria) this;
    }

    public Criteria andChannelIdLessThanOrEqualTo(String value) {
      addCriterion("channel_id <=", value, "channelId");
      return (Criteria) this;
    }

    public Criteria andChannelIdLike(String value) {
      addCriterion("channel_id like", value, "channelId");
      return (Criteria) this;
    }

    public Criteria andChannelIdNotLike(String value) {
      addCriterion("channel_id not like", value, "channelId");
      return (Criteria) this;
    }

    public Criteria andChannelIdIn(List<String> values) {
      addCriterion("channel_id in", values, "channelId");
      return (Criteria) this;
    }

    public Criteria andChannelIdNotIn(List<String> values) {
      addCriterion("channel_id not in", values, "channelId");
      return (Criteria) this;
    }

    public Criteria andChannelIdBetween(String value1, String value2) {
      addCriterion("channel_id between", value1, value2, "channelId");
      return (Criteria) this;
    }

    public Criteria andChannelIdNotBetween(String value1, String value2) {
      addCriterion("channel_id not between", value1, value2, "channelId");
      return (Criteria) this;
    }

    public Criteria andRecommenderIdIsNull() {
      addCriterion("recommender_id is null");
      return (Criteria) this;
    }

    public Criteria andRecommenderIdIsNotNull() {
      addCriterion("recommender_id is not null");
      return (Criteria) this;
    }

    public Criteria andRecommenderIdEqualTo(Long value) {
      addCriterion("recommender_id =", value, "recommenderId");
      return (Criteria) this;
    }

    public Criteria andRecommenderIdNotEqualTo(Long value) {
      addCriterion("recommender_id <>", value, "recommenderId");
      return (Criteria) this;
    }

    public Criteria andRecommenderIdGreaterThan(Long value) {
      addCriterion("recommender_id >", value, "recommenderId");
      return (Criteria) this;
    }

    public Criteria andRecommenderIdGreaterThanOrEqualTo(Long value) {
      addCriterion("recommender_id >=", value, "recommenderId");
      return (Criteria) this;
    }

    public Criteria andRecommenderIdLessThan(Long value) {
      addCriterion("recommender_id <", value, "recommenderId");
      return (Criteria) this;
    }

    public Criteria andRecommenderIdLessThanOrEqualTo(Long value) {
      addCriterion("recommender_id <=", value, "recommenderId");
      return (Criteria) this;
    }

    public Criteria andRecommenderIdIn(List<Long> values) {
      addCriterion("recommender_id in", values, "recommenderId");
      return (Criteria) this;
    }

    public Criteria andRecommenderIdNotIn(List<Long> values) {
      addCriterion("recommender_id not in", values, "recommenderId");
      return (Criteria) this;
    }

    public Criteria andRecommenderIdBetween(Long value1, Long value2) {
      addCriterion("recommender_id between", value1, value2, "recommenderId");
      return (Criteria) this;
    }

    public Criteria andRecommenderIdNotBetween(Long value1, Long value2) {
      addCriterion("recommender_id not between", value1, value2, "recommenderId");
      return (Criteria) this;
    }

    public Criteria andRecommendTimeIsNull() {
      addCriterion("recommend_time is null");
      return (Criteria) this;
    }

    public Criteria andRecommendTimeIsNotNull() {
      addCriterion("recommend_time is not null");
      return (Criteria) this;
    }

    public Criteria andRecommendTimeEqualTo(Date value) {
      addCriterion("recommend_time =", value, "recommendTime");
      return (Criteria) this;
    }

    public Criteria andRecommendTimeNotEqualTo(Date value) {
      addCriterion("recommend_time <>", value, "recommendTime");
      return (Criteria) this;
    }

    public Criteria andRecommendTimeGreaterThan(Date value) {
      addCriterion("recommend_time >", value, "recommendTime");
      return (Criteria) this;
    }

    public Criteria andRecommendTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("recommend_time >=", value, "recommendTime");
      return (Criteria) this;
    }

    public Criteria andRecommendTimeLessThan(Date value) {
      addCriterion("recommend_time <", value, "recommendTime");
      return (Criteria) this;
    }

    public Criteria andRecommendTimeLessThanOrEqualTo(Date value) {
      addCriterion("recommend_time <=", value, "recommendTime");
      return (Criteria) this;
    }

    public Criteria andRecommendTimeIn(List<Date> values) {
      addCriterion("recommend_time in", values, "recommendTime");
      return (Criteria) this;
    }

    public Criteria andRecommendTimeNotIn(List<Date> values) {
      addCriterion("recommend_time not in", values, "recommendTime");
      return (Criteria) this;
    }

    public Criteria andRecommendTimeBetween(Date value1, Date value2) {
      addCriterion("recommend_time between", value1, value2, "recommendTime");
      return (Criteria) this;
    }

    public Criteria andRecommendTimeNotBetween(Date value1, Date value2) {
      addCriterion("recommend_time not between", value1, value2, "recommendTime");
      return (Criteria) this;
    }

    public Criteria andRecommendMobileIsNull() {
      addCriterion("recommend_mobile is null");
      return (Criteria) this;
    }

    public Criteria andRecommendMobileIsNotNull() {
      addCriterion("recommend_mobile is not null");
      return (Criteria) this;
    }

    public Criteria andRecommendMobileEqualTo(String value) {
      addCriterion("recommend_mobile =", value, "recommendMobile");
      return (Criteria) this;
    }

    public Criteria andRecommendMobileNotEqualTo(String value) {
      addCriterion("recommend_mobile <>", value, "recommendMobile");
      return (Criteria) this;
    }

    public Criteria andRecommendMobileGreaterThan(String value) {
      addCriterion("recommend_mobile >", value, "recommendMobile");
      return (Criteria) this;
    }

    public Criteria andRecommendMobileGreaterThanOrEqualTo(String value) {
      addCriterion("recommend_mobile >=", value, "recommendMobile");
      return (Criteria) this;
    }

    public Criteria andRecommendMobileLessThan(String value) {
      addCriterion("recommend_mobile <", value, "recommendMobile");
      return (Criteria) this;
    }

    public Criteria andRecommendMobileLessThanOrEqualTo(String value) {
      addCriterion("recommend_mobile <=", value, "recommendMobile");
      return (Criteria) this;
    }

    public Criteria andRecommendMobileLike(String value) {
      addCriterion("recommend_mobile like", value, "recommendMobile");
      return (Criteria) this;
    }

    public Criteria andRecommendMobileNotLike(String value) {
      addCriterion("recommend_mobile not like", value, "recommendMobile");
      return (Criteria) this;
    }

    public Criteria andRecommendMobileIn(List<String> values) {
      addCriterion("recommend_mobile in", values, "recommendMobile");
      return (Criteria) this;
    }

    public Criteria andRecommendMobileNotIn(List<String> values) {
      addCriterion("recommend_mobile not in", values, "recommendMobile");
      return (Criteria) this;
    }

    public Criteria andRecommendMobileBetween(String value1, String value2) {
      addCriterion("recommend_mobile between", value1, value2, "recommendMobile");
      return (Criteria) this;
    }

    public Criteria andRecommendMobileNotBetween(String value1, String value2) {
      addCriterion("recommend_mobile not between", value1, value2, "recommendMobile");
      return (Criteria) this;
    }

    public Criteria andRealnameIsNull() {
      addCriterion("realname is null");
      return (Criteria) this;
    }

    public Criteria andRealnameIsNotNull() {
      addCriterion("realname is not null");
      return (Criteria) this;
    }

    public Criteria andRealnameEqualTo(String value) {
      addCriterion("realname =", value, "realname");
      return (Criteria) this;
    }

    public Criteria andRealnameNotEqualTo(String value) {
      addCriterion("realname <>", value, "realname");
      return (Criteria) this;
    }

    public Criteria andRealnameGreaterThan(String value) {
      addCriterion("realname >", value, "realname");
      return (Criteria) this;
    }

    public Criteria andRealnameGreaterThanOrEqualTo(String value) {
      addCriterion("realname >=", value, "realname");
      return (Criteria) this;
    }

    public Criteria andRealnameLessThan(String value) {
      addCriterion("realname <", value, "realname");
      return (Criteria) this;
    }

    public Criteria andRealnameLessThanOrEqualTo(String value) {
      addCriterion("realname <=", value, "realname");
      return (Criteria) this;
    }

    public Criteria andRealnameLike(String value) {
      addCriterion("realname like", value, "realname");
      return (Criteria) this;
    }

    public Criteria andRealnameNotLike(String value) {
      addCriterion("realname not like", value, "realname");
      return (Criteria) this;
    }

    public Criteria andRealnameIn(List<String> values) {
      addCriterion("realname in", values, "realname");
      return (Criteria) this;
    }

    public Criteria andRealnameNotIn(List<String> values) {
      addCriterion("realname not in", values, "realname");
      return (Criteria) this;
    }

    public Criteria andRealnameBetween(String value1, String value2) {
      addCriterion("realname between", value1, value2, "realname");
      return (Criteria) this;
    }

    public Criteria andRealnameNotBetween(String value1, String value2) {
      addCriterion("realname not between", value1, value2, "realname");
      return (Criteria) this;
    }

    public Criteria andIsagentIsNull() {
      addCriterion("isagent is null");
      return (Criteria) this;
    }

    public Criteria andIsagentIsNotNull() {
      addCriterion("isagent is not null");
      return (Criteria) this;
    }

    public Criteria andIsagentEqualTo(Integer value) {
      addCriterion("isagent =", value, "isagent");
      return (Criteria) this;
    }

    public Criteria andIsagentNotEqualTo(Integer value) {
      addCriterion("isagent <>", value, "isagent");
      return (Criteria) this;
    }

    public Criteria andIsagentGreaterThan(Integer value) {
      addCriterion("isagent >", value, "isagent");
      return (Criteria) this;
    }

    public Criteria andIsagentGreaterThanOrEqualTo(Integer value) {
      addCriterion("isagent >=", value, "isagent");
      return (Criteria) this;
    }

    public Criteria andIsagentLessThan(Integer value) {
      addCriterion("isagent <", value, "isagent");
      return (Criteria) this;
    }

    public Criteria andIsagentLessThanOrEqualTo(Integer value) {
      addCriterion("isagent <=", value, "isagent");
      return (Criteria) this;
    }

    public Criteria andIsagentIn(List<Integer> values) {
      addCriterion("isagent in", values, "isagent");
      return (Criteria) this;
    }

    public Criteria andIsagentNotIn(List<Integer> values) {
      addCriterion("isagent not in", values, "isagent");
      return (Criteria) this;
    }

    public Criteria andIsagentBetween(Integer value1, Integer value2) {
      addCriterion("isagent between", value1, value2, "isagent");
      return (Criteria) this;
    }

    public Criteria andIsagentNotBetween(Integer value1, Integer value2) {
      addCriterion("isagent not between", value1, value2, "isagent");
      return (Criteria) this;
    }

    public Criteria andBankCardIsNull() {
      addCriterion("bank_card is null");
      return (Criteria) this;
    }

    public Criteria andBankCardIsNotNull() {
      addCriterion("bank_card is not null");
      return (Criteria) this;
    }

    public Criteria andBankCardEqualTo(String value) {
      addCriterion("bank_card =", value, "bankCard");
      return (Criteria) this;
    }

    public Criteria andBankCardNotEqualTo(String value) {
      addCriterion("bank_card <>", value, "bankCard");
      return (Criteria) this;
    }

    public Criteria andBankCardGreaterThan(String value) {
      addCriterion("bank_card >", value, "bankCard");
      return (Criteria) this;
    }

    public Criteria andBankCardGreaterThanOrEqualTo(String value) {
      addCriterion("bank_card >=", value, "bankCard");
      return (Criteria) this;
    }

    public Criteria andBankCardLessThan(String value) {
      addCriterion("bank_card <", value, "bankCard");
      return (Criteria) this;
    }

    public Criteria andBankCardLessThanOrEqualTo(String value) {
      addCriterion("bank_card <=", value, "bankCard");
      return (Criteria) this;
    }

    public Criteria andBankCardLike(String value) {
      addCriterion("bank_card like", value, "bankCard");
      return (Criteria) this;
    }

    public Criteria andBankCardNotLike(String value) {
      addCriterion("bank_card not like", value, "bankCard");
      return (Criteria) this;
    }

    public Criteria andBankCardIn(List<String> values) {
      addCriterion("bank_card in", values, "bankCard");
      return (Criteria) this;
    }

    public Criteria andBankCardNotIn(List<String> values) {
      addCriterion("bank_card not in", values, "bankCard");
      return (Criteria) this;
    }

    public Criteria andBankCardBetween(String value1, String value2) {
      addCriterion("bank_card between", value1, value2, "bankCard");
      return (Criteria) this;
    }

    public Criteria andBankCardNotBetween(String value1, String value2) {
      addCriterion("bank_card not between", value1, value2, "bankCard");
      return (Criteria) this;
    }

    public Criteria andSubscribeIsNull() {
      addCriterion("subscribe is null");
      return (Criteria) this;
    }

    public Criteria andSubscribeIsNotNull() {
      addCriterion("subscribe is not null");
      return (Criteria) this;
    }

    public Criteria andSubscribeEqualTo(Integer value) {
      addCriterion("subscribe =", value, "subscribe");
      return (Criteria) this;
    }

    public Criteria andSubscribeNotEqualTo(Integer value) {
      addCriterion("subscribe <>", value, "subscribe");
      return (Criteria) this;
    }

    public Criteria andSubscribeGreaterThan(Integer value) {
      addCriterion("subscribe >", value, "subscribe");
      return (Criteria) this;
    }

    public Criteria andSubscribeGreaterThanOrEqualTo(Integer value) {
      addCriterion("subscribe >=", value, "subscribe");
      return (Criteria) this;
    }

    public Criteria andSubscribeLessThan(Integer value) {
      addCriterion("subscribe <", value, "subscribe");
      return (Criteria) this;
    }

    public Criteria andSubscribeLessThanOrEqualTo(Integer value) {
      addCriterion("subscribe <=", value, "subscribe");
      return (Criteria) this;
    }

    public Criteria andSubscribeIn(List<Integer> values) {
      addCriterion("subscribe in", values, "subscribe");
      return (Criteria) this;
    }

    public Criteria andSubscribeNotIn(List<Integer> values) {
      addCriterion("subscribe not in", values, "subscribe");
      return (Criteria) this;
    }

    public Criteria andSubscribeBetween(Integer value1, Integer value2) {
      addCriterion("subscribe between", value1, value2, "subscribe");
      return (Criteria) this;
    }

    public Criteria andSubscribeNotBetween(Integer value1, Integer value2) {
      addCriterion("subscribe not between", value1, value2, "subscribe");
      return (Criteria) this;
    }

    public Criteria andThirdpartyAccountIsNull() {
      addCriterion("thirdparty_account is null");
      return (Criteria) this;
    }

    public Criteria andThirdpartyAccountIsNotNull() {
      addCriterion("thirdparty_account is not null");
      return (Criteria) this;
    }

    public Criteria andThirdpartyAccountEqualTo(String value) {
      addCriterion("thirdparty_account =", value, "thirdpartyAccount");
      return (Criteria) this;
    }

    public Criteria andThirdpartyAccountNotEqualTo(String value) {
      addCriterion("thirdparty_account <>", value, "thirdpartyAccount");
      return (Criteria) this;
    }

    public Criteria andThirdpartyAccountGreaterThan(String value) {
      addCriterion("thirdparty_account >", value, "thirdpartyAccount");
      return (Criteria) this;
    }

    public Criteria andThirdpartyAccountGreaterThanOrEqualTo(String value) {
      addCriterion("thirdparty_account >=", value, "thirdpartyAccount");
      return (Criteria) this;
    }

    public Criteria andThirdpartyAccountLessThan(String value) {
      addCriterion("thirdparty_account <", value, "thirdpartyAccount");
      return (Criteria) this;
    }

    public Criteria andThirdpartyAccountLessThanOrEqualTo(String value) {
      addCriterion("thirdparty_account <=", value, "thirdpartyAccount");
      return (Criteria) this;
    }

    public Criteria andThirdpartyAccountLike(String value) {
      addCriterion("thirdparty_account like", value, "thirdpartyAccount");
      return (Criteria) this;
    }

    public Criteria andThirdpartyAccountNotLike(String value) {
      addCriterion("thirdparty_account not like", value, "thirdpartyAccount");
      return (Criteria) this;
    }

    public Criteria andThirdpartyAccountIn(List<String> values) {
      addCriterion("thirdparty_account in", values, "thirdpartyAccount");
      return (Criteria) this;
    }

    public Criteria andThirdpartyAccountNotIn(List<String> values) {
      addCriterion("thirdparty_account not in", values, "thirdpartyAccount");
      return (Criteria) this;
    }

    public Criteria andThirdpartyAccountBetween(String value1, String value2) {
      addCriterion("thirdparty_account between", value1, value2, "thirdpartyAccount");
      return (Criteria) this;
    }

    public Criteria andThirdpartyAccountNotBetween(String value1, String value2) {
      addCriterion("thirdparty_account not between", value1, value2, "thirdpartyAccount");
      return (Criteria) this;
    }

    public Criteria andRongyunTokenIsNull() {
      addCriterion("rongyun_token is null");
      return (Criteria) this;
    }

    public Criteria andRongyunTokenIsNotNull() {
      addCriterion("rongyun_token is not null");
      return (Criteria) this;
    }

    public Criteria andRongyunTokenEqualTo(String value) {
      addCriterion("rongyun_token =", value, "rongyunToken");
      return (Criteria) this;
    }

    public Criteria andRongyunTokenNotEqualTo(String value) {
      addCriterion("rongyun_token <>", value, "rongyunToken");
      return (Criteria) this;
    }

    public Criteria andRongyunTokenGreaterThan(String value) {
      addCriterion("rongyun_token >", value, "rongyunToken");
      return (Criteria) this;
    }

    public Criteria andRongyunTokenGreaterThanOrEqualTo(String value) {
      addCriterion("rongyun_token >=", value, "rongyunToken");
      return (Criteria) this;
    }

    public Criteria andRongyunTokenLessThan(String value) {
      addCriterion("rongyun_token <", value, "rongyunToken");
      return (Criteria) this;
    }

    public Criteria andRongyunTokenLessThanOrEqualTo(String value) {
      addCriterion("rongyun_token <=", value, "rongyunToken");
      return (Criteria) this;
    }

    public Criteria andRongyunTokenLike(String value) {
      addCriterion("rongyun_token like", value, "rongyunToken");
      return (Criteria) this;
    }

    public Criteria andRongyunTokenNotLike(String value) {
      addCriterion("rongyun_token not like", value, "rongyunToken");
      return (Criteria) this;
    }

    public Criteria andRongyunTokenIn(List<String> values) {
      addCriterion("rongyun_token in", values, "rongyunToken");
      return (Criteria) this;
    }

    public Criteria andRongyunTokenNotIn(List<String> values) {
      addCriterion("rongyun_token not in", values, "rongyunToken");
      return (Criteria) this;
    }

    public Criteria andRongyunTokenBetween(String value1, String value2) {
      addCriterion("rongyun_token between", value1, value2, "rongyunToken");
      return (Criteria) this;
    }

    public Criteria andRongyunTokenNotBetween(String value1, String value2) {
      addCriterion("rongyun_token not between", value1, value2, "rongyunToken");
      return (Criteria) this;
    }

    public Criteria andDeviceTokenIsNull() {
      addCriterion("device_token is null");
      return (Criteria) this;
    }

    public Criteria andDeviceTokenIsNotNull() {
      addCriterion("device_token is not null");
      return (Criteria) this;
    }

    public Criteria andDeviceTokenEqualTo(String value) {
      addCriterion("device_token =", value, "deviceToken");
      return (Criteria) this;
    }

    public Criteria andDeviceTokenNotEqualTo(String value) {
      addCriterion("device_token <>", value, "deviceToken");
      return (Criteria) this;
    }

    public Criteria andDeviceTokenGreaterThan(String value) {
      addCriterion("device_token >", value, "deviceToken");
      return (Criteria) this;
    }

    public Criteria andDeviceTokenGreaterThanOrEqualTo(String value) {
      addCriterion("device_token >=", value, "deviceToken");
      return (Criteria) this;
    }

    public Criteria andDeviceTokenLessThan(String value) {
      addCriterion("device_token <", value, "deviceToken");
      return (Criteria) this;
    }

    public Criteria andDeviceTokenLessThanOrEqualTo(String value) {
      addCriterion("device_token <=", value, "deviceToken");
      return (Criteria) this;
    }

    public Criteria andDeviceTokenLike(String value) {
      addCriterion("device_token like", value, "deviceToken");
      return (Criteria) this;
    }

    public Criteria andDeviceTokenNotLike(String value) {
      addCriterion("device_token not like", value, "deviceToken");
      return (Criteria) this;
    }

    public Criteria andDeviceTokenIn(List<String> values) {
      addCriterion("device_token in", values, "deviceToken");
      return (Criteria) this;
    }

    public Criteria andDeviceTokenNotIn(List<String> values) {
      addCriterion("device_token not in", values, "deviceToken");
      return (Criteria) this;
    }

    public Criteria andDeviceTokenBetween(String value1, String value2) {
      addCriterion("device_token between", value1, value2, "deviceToken");
      return (Criteria) this;
    }

    public Criteria andDeviceTokenNotBetween(String value1, String value2) {
      addCriterion("device_token not between", value1, value2, "deviceToken");
      return (Criteria) this;
    }

    public Criteria andCityAreaIsNull() {
      addCriterion("city_area is null");
      return (Criteria) this;
    }

    public Criteria andCityAreaIsNotNull() {
      addCriterion("city_area is not null");
      return (Criteria) this;
    }

    public Criteria andCityAreaEqualTo(String value) {
      addCriterion("city_area =", value, "cityArea");
      return (Criteria) this;
    }

    public Criteria andCityAreaNotEqualTo(String value) {
      addCriterion("city_area <>", value, "cityArea");
      return (Criteria) this;
    }

    public Criteria andCityAreaGreaterThan(String value) {
      addCriterion("city_area >", value, "cityArea");
      return (Criteria) this;
    }

    public Criteria andCityAreaGreaterThanOrEqualTo(String value) {
      addCriterion("city_area >=", value, "cityArea");
      return (Criteria) this;
    }

    public Criteria andCityAreaLessThan(String value) {
      addCriterion("city_area <", value, "cityArea");
      return (Criteria) this;
    }

    public Criteria andCityAreaLessThanOrEqualTo(String value) {
      addCriterion("city_area <=", value, "cityArea");
      return (Criteria) this;
    }

    public Criteria andCityAreaLike(String value) {
      addCriterion("city_area like", value, "cityArea");
      return (Criteria) this;
    }

    public Criteria andCityAreaNotLike(String value) {
      addCriterion("city_area not like", value, "cityArea");
      return (Criteria) this;
    }

    public Criteria andCityAreaIn(List<String> values) {
      addCriterion("city_area in", values, "cityArea");
      return (Criteria) this;
    }

    public Criteria andCityAreaNotIn(List<String> values) {
      addCriterion("city_area not in", values, "cityArea");
      return (Criteria) this;
    }

    public Criteria andCityAreaBetween(String value1, String value2) {
      addCriterion("city_area between", value1, value2, "cityArea");
      return (Criteria) this;
    }

    public Criteria andCityAreaNotBetween(String value1, String value2) {
      addCriterion("city_area not between", value1, value2, "cityArea");
      return (Criteria) this;
    }

    public Criteria andAuthRealnameIsNull() {
      addCriterion("auth_realname is null");
      return (Criteria) this;
    }

    public Criteria andAuthRealnameIsNotNull() {
      addCriterion("auth_realname is not null");
      return (Criteria) this;
    }

    public Criteria andAuthRealnameEqualTo(String value) {
      addCriterion("auth_realname =", value, "authRealname");
      return (Criteria) this;
    }

    public Criteria andAuthRealnameNotEqualTo(String value) {
      addCriterion("auth_realname <>", value, "authRealname");
      return (Criteria) this;
    }

    public Criteria andAuthRealnameGreaterThan(String value) {
      addCriterion("auth_realname >", value, "authRealname");
      return (Criteria) this;
    }

    public Criteria andAuthRealnameGreaterThanOrEqualTo(String value) {
      addCriterion("auth_realname >=", value, "authRealname");
      return (Criteria) this;
    }

    public Criteria andAuthRealnameLessThan(String value) {
      addCriterion("auth_realname <", value, "authRealname");
      return (Criteria) this;
    }

    public Criteria andAuthRealnameLessThanOrEqualTo(String value) {
      addCriterion("auth_realname <=", value, "authRealname");
      return (Criteria) this;
    }

    public Criteria andAuthRealnameLike(String value) {
      addCriterion("auth_realname like", value, "authRealname");
      return (Criteria) this;
    }

    public Criteria andAuthRealnameNotLike(String value) {
      addCriterion("auth_realname not like", value, "authRealname");
      return (Criteria) this;
    }

    public Criteria andAuthRealnameIn(List<String> values) {
      addCriterion("auth_realname in", values, "authRealname");
      return (Criteria) this;
    }

    public Criteria andAuthRealnameNotIn(List<String> values) {
      addCriterion("auth_realname not in", values, "authRealname");
      return (Criteria) this;
    }

    public Criteria andAuthRealnameBetween(String value1, String value2) {
      addCriterion("auth_realname between", value1, value2, "authRealname");
      return (Criteria) this;
    }

    public Criteria andAuthRealnameNotBetween(String value1, String value2) {
      addCriterion("auth_realname not between", value1, value2, "authRealname");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table user_info
   *
   * @mbggenerated do_not_delete_during_merge
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator.
   * This class corresponds to the database table user_info
   *
   * @mbggenerated
   */
  public static class Criterion {
    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}